### ISSUE TITLE
you should except ".vs" folder

### ISSUE THREAD

**Issue by Bian-Sh** [JonathanTremblay/UnityExportToZip#1]
https://github.com/JonathanTremblay/UnityExportToZip/blob/bf528f629490608a7643bfb52673e12c27e9c2d2/Editor/ExportProjectToZip.cs#L88

    List<string> exceptionList = new List<string>() { GetFolderFullPath(".vs"), GetFolderFullPath(".git"), GetFolderFullPath("Library"), GetFolderFullPath("Logs"), GetFolderFullPath("obj"), GetFolderFullPath("Obj"), GetFolderFullPath("Temp") };

**Comment by JonathanTremblay** [comment]
You are right! Thank you for raising this issue, @Bian-Sh. I will make the change. 🙂

**Comment by Bian-Sh** [comment]
how about this folder : .github .vscode .rider  as well as this file: .csproj 
maybe you can allow us to set the folder except by using setting providers.

**Comment by JonathanTremblay** [comment]
I'll exclude the .vscode folder too.
I'm not sure I want to exclude all the other folders, since they are quite small and each new code editor could create their own. Your idea of ​​creating a preference to exclude folders is good. On the other hand, I want to keep the code simple. I'll think about it for a future more significant version.
Thanks again!

**Comment by JonathanTremblay** [comment]
**Version 1.1.2** is now available (currently on _GitHub_ only).
It features new options to exclude specific folders or extensions.
By default, it now excludes the following folders: `.git`, `.vs`, `.vscode`, `Build`, `Builds`, `Logs`, `obj`, `Obj`, `UserSettings`, `Temp`. 
It also excludes all `.gitignore`, `.csproj`, `.sln`, and `.zip` files at the top level of the project.
![image](https://github.com/user-attachments/assets/c7c2a618-872d-4bee-8bb0-15e714497384)
Thanks to @Bian-Sh for his suggestions!
